### ISSUE TITLE
uwsgi script invokes uwsgi twice

### ISSUE THREAD

**Issue by lsh-0** [elifesciences/iiif-formula#3]
is this line intentional? 
https://github.com/elifesciences/iiif-formula/blob/master/salt/iiif/config/etc-init-uwsgi-loris.conf#L4

pinging @giorgiosironi

**Comment by giorgiosironi** [comment]
Looks like a copy&paste error, first one can be removed. The last exec wins I think (in fact we see data on New Relic).

**Comment by lsh-0** [comment]
this file doesn't exist: /opt/loris/newrelic.ini

**Comment by giorgiosironi** [comment]
That should be created by: https://github.com/elifesciences/builder-base-formula/blob/master/elife/newrelic-python.sls#L12
which is configured here: https://github.com/elifesciences/builder-private/blob/master/salt/top.sls#L464

**Comment by lsh-0** [comment]
that line is disabled in the formula

**Comment by giorgiosironi** [comment]
Yeah, the pattern usually is:
- on Vagrant, the `newrelic-*` states are commented as there is no license deployed. Therefore there would be a failing process trying to upload metrics (and we don't want metrics from Vagrant anyway). The project is expected to work without New Relic as it shouldn't be a dependency.
- on AWS, builder-private's `top.sls` enables the `newrelic-*` states, either as part of `*` or of a particular project `iiif--*` matcher.

**Comment by lsh-0** [comment]
while I have you here, https://1604test1--iiif.elifesciences.org/ appears to be up and working, but this smoke.sh state isn't working: 
```
# smoke_url_ok "https://localhost/"
> https://localhost/
    [FAIL] 2xx Response code
```

and it looks like `localhost` is hardcoded. any clues here?

**Comment by giorgiosironi** [comment]
This is meant to be executed from inside the server, that's why `localhost`. It tries to load `/` over the local nginx, which is forwarded to uwsgi as for all other projects. It checks that the response is `200` or similar, but this is failing. I would look at:
```
/var/log/nginx/loris.access.log # status codes
/var/log/uwsgi-loris.log # stack traces, and other Python application logging
```

**Comment by lsh-0** [comment]
spent some time debugging that smoke.sh repo (it's a pos), but the problem lies here: https://github.com/elifesciences/iiif-formula/blob/master/salt/iiif/config/etc-nginx-sites-enabled-loris.conf#L14

I'm going to modify iiif project to always listen on 80 internally so having nginx listen on port 80 won't affect security

**Comment by lsh-0** [comment]
fix: https://github.com/elifesciences/iiif-formula/pull/4/files#diff-a61a92ce81bb1fe7fd89fd1fec9e11b3R12

suggestion: https://github.com/elifesciences/builder/pull/187/files
